### ISSUE TITLE
Это можно вынести в компонент PeopleField

### ISSUE THREAD

**Issue by pavliha** [LexaLukivka/partymakerFrontend#10]
https://github.com/LexaLukivka/partymakerFrontend/blob/0bf60eb76b57eec33ec48ef8e81a89fa8dee9b3b/src/components/%40patry-create/PartyCardForm/index.jsx#L144

**Comment by LexaLukivka** [comment]
Не самая лучшая идея, как на мой взгляд 
Так как для этого отдельного компонента нужно создавать те же функции this.hasError и другие

**Comment by pavliha** [comment]
Это хорошая идея если всё правильно продумать. и скрыть всё так что бы эти 2 поля вели себя как отдельный компонент. Ну ладно. Это займет много времени а пользы не много
