### ISSUE TITLE
Переименовать редюсер в соответсвии стилем

### ISSUE THREAD

**Issue by pavliha** [LexaLukivka/partymakerFrontend#19]
https://github.com/LexaLukivka/partymakerFrontend/blob/0bf60eb76b57eec33ec48ef8e81a89fa8dee9b3b/src/redux/index.js#L11

У нас на проекте все редюсеры с приставкой редюсер. Что бы мы понимали что это именно редюсер а не какой-то левый обьект

**Comment by LexaLukivka** [comment]
так все отлично?
От него уже идет переход дальше на создание получение и т.д.

**Comment by pavliha** [comment]
Нет не отлично partyReducer, settingReducer вот так у нас
